spring:
  application:
    name: pargasys-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/anamay1992/pargasys-config-server
          default-label: main
          clone-on-start: true
server:
  port: 8888