spring:
  application:
    name: pargasys-auth
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888
  sleuth:
    async:
      enabled: true
  zipkin:
    base-url: http://localhost:9411
server:
  port: 8082
management:
  endpoints:
    web:
      exposure:
        include: "*"
